[package]
name = "mono_framework_rs"
version = "0.1.0"
authors = ["Sune Kirkeby <mig@ibofobi.dk>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
alloc_malloc = { path = "../alloc_malloc" }
